// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrckbkovwzlmnhpculca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyY2tia292d3psbW5ocGN1bGNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNTA0NTMsImV4cCI6MjA1MTgyNjQ1M30.ORACOMKn0pFzkR3Av68xqm4hevUASpKuj0ur8Z5cars";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);